### ISSUE TITLE
مشکل استفاده از فایل

### ISSUE THREAD

**Issue by MD-97** [peymanebrahimi/AngularMaterialJalaliDate#6]
سلام
در انگولار 10 به ارور زیر بر خوردم

alali_moment_formats.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

jalali-moment-date-adapter.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

**Comment by peymanebrahimi** [comment]
سلام
محتوای 3 فایل زیر رو در پروژه خودتون کپی کنید
jalali-moment-date-adapter.ts
jalali_moment_formats.ts
mat-core.module.ts

در ضمن به جای این کار میتونید از پکیج زیر استفاده کنید.
https://github.com/peymanebrahimi/MaterialJalaliMomentAdapter
